//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CaregiverLite.Views.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class CareGiver {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CareGiver() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CaregiverLite.Views.Resources.CareGiver", typeof(CareGiver).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ADD CAREGIVER.
        /// </summary>
        public static string ButtonAddCareGiver {
            get {
                return ResourceManager.GetString("ButtonAddCareGiver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add New.
        /// </summary>
        public static string ButtonAddNew {
            get {
                return ResourceManager.GetString("ButtonAddNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Time Slot.
        /// </summary>
        public static string ButtonAddTimeSlot {
            get {
                return ResourceManager.GetString("ButtonAddTimeSlot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to APPROVE.
        /// </summary>
        public static string ButtonApprove {
            get {
                return ResourceManager.GetString("ButtonApprove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel All Appointment.
        /// </summary>
        public static string ButtonCancelAllAppointment {
            get {
                return ResourceManager.GetString("ButtonCancelAllAppointment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string ButtonClose {
            get {
                return ResourceManager.GetString("ButtonClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DELETE.
        /// </summary>
        public static string ButtonDelete {
            get {
                return ResourceManager.GetString("ButtonDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document.
        /// </summary>
        public static string ButtonDocument {
            get {
                return ResourceManager.GetString("ButtonDocument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Profile.
        /// </summary>
        public static string ButtonEditProfile {
            get {
                return ResourceManager.GetString("ButtonEditProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Schedule.
        /// </summary>
        public static string ButtonEditSchedule {
            get {
                return ResourceManager.GetString("ButtonEditSchedule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next.
        /// </summary>
        public static string ButtonNext {
            get {
                return ResourceManager.GetString("ButtonNext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Previous.
        /// </summary>
        public static string ButtonPrevious {
            get {
                return ResourceManager.GetString("ButtonPrevious", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile.
        /// </summary>
        public static string ButtonProfile {
            get {
                return ResourceManager.GetString("ButtonProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to REJECT.
        /// </summary>
        public static string ButtonReject {
            get {
                return ResourceManager.GetString("ButtonReject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Changes.
        /// </summary>
        public static string ButtonSaveChanges {
            get {
                return ResourceManager.GetString("ButtonSaveChanges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Schedule.
        /// </summary>
        public static string ButtonSchedule {
            get {
                return ResourceManager.GetString("ButtonSchedule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send &amp; Verify.
        /// </summary>
        public static string ButtonSendNVerify {
            get {
                return ResourceManager.GetString("ButtonSendNVerify", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update.
        /// </summary>
        public static string ButtonUpdate {
            get {
                return ResourceManager.GetString("ButtonUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile.
        /// </summary>
        public static string ButtonViewProfile {
            get {
                return ResourceManager.GetString("ButtonViewProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Caregiver Profile Details.
        /// </summary>
        public static string CareGiverProfileDetails {
            get {
                return ResourceManager.GetString("CareGiverProfileDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Office:.
        /// </summary>
        public static string FilterOffice {
            get {
                return ResourceManager.GetString("FilterOffice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Caregiver.
        /// </summary>
        public static string HeaderAddCareGiver {
            get {
                return ResourceManager.GetString("HeaderAddCareGiver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Time Slot.
        /// </summary>
        public static string HeaderAddTimeSlots {
            get {
                return ResourceManager.GetString("HeaderAddTimeSlots", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Caregiver Details.
        /// </summary>
        public static string HeaderCareGiverDetail {
            get {
                return ResourceManager.GetString("HeaderCareGiverDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Caregiver List.
        /// </summary>
        public static string HeaderCareGiverList {
            get {
                return ResourceManager.GetString("HeaderCareGiverList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit CareGiver.
        /// </summary>
        public static string HeaderEditCareGiver {
            get {
                return ResourceManager.GetString("HeaderEditCareGiver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Schedule.
        /// </summary>
        public static string HeaderEditSchedule {
            get {
                return ResourceManager.GetString("HeaderEditSchedule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send Approval.
        /// </summary>
        public static string HeaderSendApproval {
            get {
                return ResourceManager.GetString("HeaderSendApproval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unavailability Request List.
        /// </summary>
        public static string HeaderUnavailabilityRequestList {
            get {
                return ResourceManager.GetString("HeaderUnavailabilityRequestList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View Appointments.
        /// </summary>
        public static string HeaderViewAppointments {
            get {
                return ResourceManager.GetString("HeaderViewAppointments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View Certificate.
        /// </summary>
        public static string HeaderViewCertificate {
            get {
                return ResourceManager.GetString("HeaderViewCertificate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View Schedule.
        /// </summary>
        public static string HeaderViewSchedule {
            get {
                return ResourceManager.GetString("HeaderViewSchedule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From Time.
        /// </summary>
        public static string LabelFromTime {
            get {
                return ResourceManager.GetString("LabelFromTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register.
        /// </summary>
        public static string LabelHeaderRegister {
            get {
                return ResourceManager.GetString("LabelHeaderRegister", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ServiceRadius.
        /// </summary>
        public static string LabelHeaderServiceRadius {
            get {
                return ResourceManager.GetString("LabelHeaderServiceRadius", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service Types.
        /// </summary>
        public static string LabelHeaderServices {
            get {
                return ResourceManager.GetString("LabelHeaderServices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Photo Upload.
        /// </summary>
        public static string LabelPhotoUpload {
            get {
                return ResourceManager.GetString("LabelPhotoUpload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 12:00 AM  TO 5:00 AM.
        /// </summary>
        public static string LabelTimeSlot1 {
            get {
                return ResourceManager.GetString("LabelTimeSlot1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 05:00 AM TO 12:00 PM.
        /// </summary>
        public static string LabelTimeSlot2 {
            get {
                return ResourceManager.GetString("LabelTimeSlot2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 12:00 PM TO 08:00 PM.
        /// </summary>
        public static string LabelTimeSlot3 {
            get {
                return ResourceManager.GetString("LabelTimeSlot3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 08:00 PM TO 11:59 PM.
        /// </summary>
        public static string LabelTimeSlot4 {
            get {
                return ResourceManager.GetString("LabelTimeSlot4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time Slots.
        /// </summary>
        public static string LabelTimeSlots {
            get {
                return ResourceManager.GetString("LabelTimeSlots", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To Time.
        /// </summary>
        public static string LabelToTime {
            get {
                return ResourceManager.GetString("LabelToTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Video Upload.
        /// </summary>
        public static string LabelVideoUpload {
            get {
                return ResourceManager.GetString("LabelVideoUpload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Whole Day.
        /// </summary>
        public static string LabelWholeDay {
            get {
                return ResourceManager.GetString("LabelWholeDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter reject comment.
        /// </summary>
        public static string MsgAddCommentError {
            get {
                return ResourceManager.GetString("MsgAddCommentError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pleaser select From time and To time to add time slot.
        /// </summary>
        public static string MsgAddTimeSlotError {
            get {
                return ResourceManager.GetString("MsgAddTimeSlotError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please cancel all appointments first.
        /// </summary>
        public static string MsgCancelAppointmentError {
            get {
                return ResourceManager.GetString("MsgCancelAppointmentError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete.?.
        /// </summary>
        public static string MsgDeleteConfirmation {
            get {
                return ResourceManager.GetString("MsgDeleteConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is some error. Please try again later.
        /// </summary>
        public static string MsgError {
            get {
                return ResourceManager.GetString("MsgError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New password must be different from old password..
        /// </summary>
        public static string NewPasswordMatch {
            get {
                return ResourceManager.GetString("NewPasswordMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Address.
        /// </summary>
        public static string PlaceHolderAddress {
            get {
                return ResourceManager.GetString("PlaceHolderAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter City.
        /// </summary>
        public static string PlaceHolderCity {
            get {
                return ResourceManager.GetString("PlaceHolderCity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Education and Qualifications.
        /// </summary>
        public static string PlaceHolderEducation {
            get {
                return ResourceManager.GetString("PlaceHolderEducation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Email.
        /// </summary>
        public static string PlaceHolderEmail {
            get {
                return ResourceManager.GetString("PlaceHolderEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Reimbursement Charge.
        /// </summary>
        public static string PlaceHolderHourRate {
            get {
                return ResourceManager.GetString("PlaceHolderHourRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Name.
        /// </summary>
        public static string PlaceHolderName {
            get {
                return ResourceManager.GetString("PlaceHolderName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string PlaceHolderPassword {
            get {
                return ResourceManager.GetString("PlaceHolderPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Phone no..
        /// </summary>
        public static string PlaceHolderPhone {
            get {
                return ResourceManager.GetString("PlaceHolderPhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Comment.
        /// </summary>
        public static string PlaceHolderRejectComment {
            get {
                return ResourceManager.GetString("PlaceHolderRejectComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter State.
        /// </summary>
        public static string PlaceHolderState {
            get {
                return ResourceManager.GetString("PlaceHolderState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Street.
        /// </summary>
        public static string PlaceHolderStreet {
            get {
                return ResourceManager.GetString("PlaceHolderStreet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Username.
        /// </summary>
        public static string PlaceHolderUserName {
            get {
                return ResourceManager.GetString("PlaceHolderUserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Zip Code.
        /// </summary>
        public static string PlaceHolderZipCode {
            get {
                return ResourceManager.GetString("PlaceHolderZipCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter address.
        /// </summary>
        public static string RequiredMsgAddress {
            get {
                return ResourceManager.GetString("RequiredMsgAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter city.
        /// </summary>
        public static string RequiredMsgCity {
            get {
                return ResourceManager.GetString("RequiredMsgCity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter education and qualifications.
        /// </summary>
        public static string RequiredMsgEducation {
            get {
                return ResourceManager.GetString("RequiredMsgEducation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter email.
        /// </summary>
        public static string RequiredMsgEmail {
            get {
                return ResourceManager.GetString("RequiredMsgEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email is already exists.
        /// </summary>
        public static string RequiredMsgEmailExists {
            get {
                return ResourceManager.GetString("RequiredMsgEmailExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter reimbursement charge.
        /// </summary>
        public static string RequiredMsgHoursRate {
            get {
                return ResourceManager.GetString("RequiredMsgHoursRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter name .
        /// </summary>
        public static string RequiredMsgName {
            get {
                return ResourceManager.GetString("RequiredMsgName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter password.
        /// </summary>
        public static string RequiredMsgPassword {
            get {
                return ResourceManager.GetString("RequiredMsgPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter phone no.
        /// </summary>
        public static string RequiredMsgPhone {
            get {
                return ResourceManager.GetString("RequiredMsgPhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please upload profile image.
        /// </summary>
        public static string RequiredMsgProfileImage {
            get {
                return ResourceManager.GetString("RequiredMsgProfileImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter Re-Type password.
        /// </summary>
        public static string RequiredMsgReTypePassword {
            get {
                return ResourceManager.GetString("RequiredMsgReTypePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select service radius.
        /// </summary>
        public static string RequiredMsgServiceRadius {
            get {
                return ResourceManager.GetString("RequiredMsgServiceRadius", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select services.
        /// </summary>
        public static string RequiredMsgServices {
            get {
                return ResourceManager.GetString("RequiredMsgServices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter state.
        /// </summary>
        public static string RequiredMsgState {
            get {
                return ResourceManager.GetString("RequiredMsgState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter street.
        /// </summary>
        public static string RequiredMsgStreet {
            get {
                return ResourceManager.GetString("RequiredMsgStreet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter user name.
        /// </summary>
        public static string RequiredMsgUsername {
            get {
                return ResourceManager.GetString("RequiredMsgUsername", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User name is already exists.
        /// </summary>
        public static string RequiredMsgUsernameExists {
            get {
                return ResourceManager.GetString("RequiredMsgUsernameExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter zip code.
        /// </summary>
        public static string RequiredMsgZipCode {
            get {
                return ResourceManager.GetString("RequiredMsgZipCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter your old password.
        /// </summary>
        public static string RequiredOldPassWord {
            get {
                return ResourceManager.GetString("RequiredOldPassWord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter valid password.
        /// </summary>
        public static string RequiredOldPassWordNotMatch {
            get {
                return ResourceManager.GetString("RequiredOldPassWordNotMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Action.
        /// </summary>
        public static string TableHeaderAction {
            get {
                return ResourceManager.GetString("TableHeaderAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address.
        /// </summary>
        public static string TableHeaderAddress {
            get {
                return ResourceManager.GetString("TableHeaderAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to City.
        /// </summary>
        public static string TableHeaderCity {
            get {
                return ResourceManager.GetString("TableHeaderCity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        public static string TableHeaderDate {
            get {
                return ResourceManager.GetString("TableHeaderDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Education and Qualifications.
        /// </summary>
        public static string TableHeaderEducation {
            get {
                return ResourceManager.GetString("TableHeaderEducation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string TableHeaderEmail {
            get {
                return ResourceManager.GetString("TableHeaderEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fields.
        /// </summary>
        public static string TableHeaderFieldsName {
            get {
                return ResourceManager.GetString("TableHeaderFieldsName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From Date &amp; Time.
        /// </summary>
        public static string TableHeaderFromDateTime {
            get {
                return ResourceManager.GetString("TableHeaderFromDateTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reimbursement Charge (To be charged to patient):.
        /// </summary>
        public static string TableHeaderHourRate {
            get {
                return ResourceManager.GetString("TableHeaderHourRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inserted On.
        /// </summary>
        public static string TableHeaderInsertedOn {
            get {
                return ResourceManager.GetString("TableHeaderInsertedOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string TableHeaderName {
            get {
                return ResourceManager.GetString("TableHeaderName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Profile.
        /// </summary>
        public static string TableHeaderNewFieldsName {
            get {
                return ResourceManager.GetString("TableHeaderNewFieldsName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        public static string TableHeaderNo {
            get {
                return ResourceManager.GetString("TableHeaderNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No of Appointments.
        /// </summary>
        public static string TableHeaderNoOfAppointments {
            get {
                return ResourceManager.GetString("TableHeaderNoOfAppointments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Office.
        /// </summary>
        public static string TableHeaderOffice {
            get {
                return ResourceManager.GetString("TableHeaderOffice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Old Profile.
        /// </summary>
        public static string TableHeaderOldFieldsName {
            get {
                return ResourceManager.GetString("TableHeaderOldFieldsName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string TableHeaderPassword {
            get {
                return ResourceManager.GetString("TableHeaderPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Patient Name.
        /// </summary>
        public static string TableHeaderPatientName {
            get {
                return ResourceManager.GetString("TableHeaderPatientName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone.
        /// </summary>
        public static string TableHeaderPhone {
            get {
                return ResourceManager.GetString("TableHeaderPhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Photo.
        /// </summary>
        public static string TableHeaderPhoto {
            get {
                return ResourceManager.GetString("TableHeaderPhoto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service Radius.
        /// </summary>
        public static string TableHeaderServiceRadius {
            get {
                return ResourceManager.GetString("TableHeaderServiceRadius", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service Types.
        /// </summary>
        public static string TableHeaderServices {
            get {
                return ResourceManager.GetString("TableHeaderServices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to State.
        /// </summary>
        public static string TableHeaderState {
            get {
                return ResourceManager.GetString("TableHeaderState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Street.
        /// </summary>
        public static string TableHeaderStreet {
            get {
                return ResourceManager.GetString("TableHeaderStreet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time Slot.
        /// </summary>
        public static string TableHeaderTimeSlots {
            get {
                return ResourceManager.GetString("TableHeaderTimeSlots", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Timezone.
        /// </summary>
        public static string TableHeaderTimezone {
            get {
                return ResourceManager.GetString("TableHeaderTimezone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To Date &amp; Time.
        /// </summary>
        public static string TableHeaderToDateTime {
            get {
                return ResourceManager.GetString("TableHeaderToDateTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Hours.
        /// </summary>
        public static string TableHeaderTotalHours {
            get {
                return ResourceManager.GetString("TableHeaderTotalHours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Payment.
        /// </summary>
        public static string TableHeaderTotalPayment {
            get {
                return ResourceManager.GetString("TableHeaderTotalPayment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Track Location.
        /// </summary>
        public static string TableHeaderTrackLocation {
            get {
                return ResourceManager.GetString("TableHeaderTrackLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Users ID.
        /// </summary>
        public static string TableHeaderUserID {
            get {
                return ResourceManager.GetString("TableHeaderUserID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username.
        /// </summary>
        public static string TableHeaderUserName {
            get {
                return ResourceManager.GetString("TableHeaderUserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zip Code.
        /// </summary>
        public static string TableHeaderZipCode {
            get {
                return ResourceManager.GetString("TableHeaderZipCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Caregiver.
        /// </summary>
        public static string TitleCareGiver {
            get {
                return ResourceManager.GetString("TitleCareGiver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I want to repeat this schedule for next.
        /// </summary>
        public static string txtIWantTo {
            get {
                return ResourceManager.GetString("txtIWantTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password minimum length should be 6.
        /// </summary>
        public static string ValidationMsgPassword {
            get {
                return ResourceManager.GetString("ValidationMsgPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone must be between 4 to 15 digits.
        /// </summary>
        public static string ValidationMsgPhone {
            get {
                return ResourceManager.GetString("ValidationMsgPhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zipcode minimum length should be 4.
        /// </summary>
        public static string ValidationMsgZipCode {
            get {
                return ResourceManager.GetString("ValidationMsgZipCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The field Hours Rate must be between 1 and 9999.9.
        /// </summary>
        public static string ValidMsgHoursRate {
            get {
                return ResourceManager.GetString("ValidMsgHoursRate", resourceCulture);
            }
        }
    }
}
