//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CaregiverLite.Views.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Dashboard {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Dashboard() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CaregiverLite.Views.Resources.Dashboard", typeof(Dashboard).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter.
        /// </summary>
        public static string ButtonFilter {
            get {
                return ResourceManager.GetString("ButtonFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View Large Map.
        /// </summary>
        public static string ButtonViewLargeMap {
            get {
                return ResourceManager.GetString("ButtonViewLargeMap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Appointment.
        /// </summary>
        public static string HeaderAppointment {
            get {
                return ResourceManager.GetString("HeaderAppointment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Care Giver Network.
        /// </summary>
        public static string HeaderNurseNetwork {
            get {
                return ResourceManager.GetString("HeaderNurseNetwork", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Patient App Download.
        /// </summary>
        public static string HeaderPatientAppDownload {
            get {
                return ResourceManager.GetString("HeaderPatientAppDownload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Patient Network.
        /// </summary>
        public static string HeaderPatientNetwork {
            get {
                return ResourceManager.GetString("HeaderPatientNetwork", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment Received.
        /// </summary>
        public static string HeaderPaymentReceived {
            get {
                return ResourceManager.GetString("HeaderPaymentReceived", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Projected payment in last week.
        /// </summary>
        public static string HeaderProjectedPayment {
            get {
                return ResourceManager.GetString("HeaderProjectedPayment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reschedule Alert.
        /// </summary>
        public static string HeaderRescheduleAlert {
            get {
                return ResourceManager.GetString("HeaderRescheduleAlert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reschedule Approval Alerts.
        /// </summary>
        public static string HeaderRescheduleApprovalAlerts {
            get {
                return ResourceManager.GetString("HeaderRescheduleApprovalAlerts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View Map.
        /// </summary>
        public static string HeaderViewMap {
            get {
                return ResourceManager.GetString("HeaderViewMap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Care Giver.
        /// </summary>
        public static string LabelCareGiver {
            get {
                return ResourceManager.GetString("LabelCareGiver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From Date.
        /// </summary>
        public static string LabelFromDateTime {
            get {
                return ResourceManager.GetString("LabelFromDateTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Patient Name.
        /// </summary>
        public static string LabelPatientName {
            get {
                return ResourceManager.GetString("LabelPatientName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To Date .
        /// </summary>
        public static string LabelToDateTime {
            get {
                return ResourceManager.GetString("LabelToDateTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Zipcode.
        /// </summary>
        public static string LabelZipCode {
            get {
                return ResourceManager.GetString("LabelZipCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select From date time for care giver network.
        /// </summary>
        public static string RequiredMsgDate1 {
            get {
                return ResourceManager.GetString("RequiredMsgDate1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select To date time for care giver network.
        /// </summary>
        public static string RequiredMsgDate2 {
            get {
                return ResourceManager.GetString("RequiredMsgDate2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select From date time for patient network.
        /// </summary>
        public static string RequiredMsgDate3 {
            get {
                return ResourceManager.GetString("RequiredMsgDate3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select To date time for patient network.
        /// </summary>
        public static string RequiredMsgDate4 {
            get {
                return ResourceManager.GetString("RequiredMsgDate4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select from date  for payment received.
        /// </summary>
        public static string RequiredMsgDate5 {
            get {
                return ResourceManager.GetString("RequiredMsgDate5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select to date  for payment received.
        /// </summary>
        public static string RequiredMsgDate6 {
            get {
                return ResourceManager.GetString("RequiredMsgDate6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select from date  for Projected payment.
        /// </summary>
        public static string RequiredMsgDate7 {
            get {
                return ResourceManager.GetString("RequiredMsgDate7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select to date  for Projected payment.
        /// </summary>
        public static string RequiredMsgDate8 {
            get {
                return ResourceManager.GetString("RequiredMsgDate8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Action.
        /// </summary>
        public static string TableHeaderAction {
            get {
                return ResourceManager.GetString("TableHeaderAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alert Type.
        /// </summary>
        public static string TableHeaderAlertType {
            get {
                return ResourceManager.GetString("TableHeaderAlertType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancelled Appoinment.
        /// </summary>
        public static string TableHeaderCancelledAppoinment {
            get {
                return ResourceManager.GetString("TableHeaderCancelledAppoinment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Care Giver.
        /// </summary>
        public static string TableHeaderCareGiverName {
            get {
                return ResourceManager.GetString("TableHeaderCareGiverName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date &amp; Time.
        /// </summary>
        public static string TableHeaderDateTime {
            get {
                return ResourceManager.GetString("TableHeaderDateTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finished Jobs.
        /// </summary>
        public static string TableHeaderFinishedJobs {
            get {
                return ResourceManager.GetString("TableHeaderFinishedJobs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From Date.
        /// </summary>
        public static string TableHeaderFromDateTime {
            get {
                return ResourceManager.GetString("TableHeaderFromDateTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Patient Address.
        /// </summary>
        public static string TableHeaderPatientAddress {
            get {
                return ResourceManager.GetString("TableHeaderPatientAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Patient Name.
        /// </summary>
        public static string TableHeaderPatientName {
            get {
                return ResourceManager.GetString("TableHeaderPatientName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pending Jobs.
        /// </summary>
        public static string TableHeaderPendingJobs {
            get {
                return ResourceManager.GetString("TableHeaderPendingJobs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reschedule Status.
        /// </summary>
        public static string TableHeaderRescheduleStatus {
            get {
                return ResourceManager.GetString("TableHeaderRescheduleStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service Type.
        /// </summary>
        public static string TableHeaderServiceType {
            get {
                return ResourceManager.GetString("TableHeaderServiceType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To Date.
        /// </summary>
        public static string TableHeaderToDateTime {
            get {
                return ResourceManager.GetString("TableHeaderToDateTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Hours.
        /// </summary>
        public static string TableHeaderTotalHours {
            get {
                return ResourceManager.GetString("TableHeaderTotalHours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Payment.
        /// </summary>
        public static string TableHeaderTotalPayment {
            get {
                return ResourceManager.GetString("TableHeaderTotalPayment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zipcode.
        /// </summary>
        public static string TableHeaderZipCode {
            get {
                return ResourceManager.GetString("TableHeaderZipCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dashboard.
        /// </summary>
        public static string TitleDashboard {
            get {
                return ResourceManager.GetString("TitleDashboard", resourceCulture);
            }
        }
    }
}
