//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CaregiverLite.Views.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Dispute {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Dispute() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CaregiverLite.Views.Resources.Dispute", typeof(Dispute).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comment.
        /// </summary>
        public static string ButtonComment {
            get {
                return ResourceManager.GetString("ButtonComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm &amp; Pay.
        /// </summary>
        public static string ButtonConfirmPay {
            get {
                return ResourceManager.GetString("ButtonConfirmPay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pay.
        /// </summary>
        public static string ButtonPay {
            get {
                return ResourceManager.GetString("ButtonPay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pending.
        /// </summary>
        public static string ButtonPending {
            get {
                return ResourceManager.GetString("ButtonPending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resolved.
        /// </summary>
        public static string ButtonResolved {
            get {
                return ResourceManager.GetString("ButtonResolved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submit.
        /// </summary>
        public static string ButtonSubmit {
            get {
                return ResourceManager.GetString("ButtonSubmit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Comment.
        /// </summary>
        public static string HeaderAddComment {
            get {
                return ResourceManager.GetString("HeaderAddComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dispute List.
        /// </summary>
        public static string HeaderDisputeList {
            get {
                return ResourceManager.GetString("HeaderDisputeList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment Details.
        /// </summary>
        public static string HeaderPaymentDetails {
            get {
                return ResourceManager.GetString("HeaderPaymentDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount.
        /// </summary>
        public static string LabelAmount {
            get {
                return ResourceManager.GetString("LabelAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Card Holder Name.
        /// </summary>
        public static string LabelCardHolderName {
            get {
                return ResourceManager.GetString("LabelCardHolderName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Card Number.
        /// </summary>
        public static string LabelCardNumber {
            get {
                return ResourceManager.GetString("LabelCardNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        public static string LabelDate {
            get {
                return ResourceManager.GetString("LabelDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Due Payment.
        /// </summary>
        public static string LabelDuePayment {
            get {
                return ResourceManager.GetString("LabelDuePayment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string LabelEmail {
            get {
                return ResourceManager.GetString("LabelEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From Time.
        /// </summary>
        public static string LabelFromTime {
            get {
                return ResourceManager.GetString("LabelFromTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hours Rate.
        /// </summary>
        public static string LabelHoursRate {
            get {
                return ResourceManager.GetString("LabelHoursRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Month.
        /// </summary>
        public static string LabelMonth {
            get {
                return ResourceManager.GetString("LabelMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paid Amount.
        /// </summary>
        public static string LabelPaidAmount {
            get {
                return ResourceManager.GetString("LabelPaidAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Hours.
        /// </summary>
        public static string LabelTotalHours {
            get {
                return ResourceManager.GetString("LabelTotalHours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Payment.
        /// </summary>
        public static string LabelTotalPayment {
            get {
                return ResourceManager.GetString("LabelTotalPayment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To Time.
        /// </summary>
        public static string LabelToTime {
            get {
                return ResourceManager.GetString("LabelToTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Year.
        /// </summary>
        public static string LabelYear {
            get {
                return ResourceManager.GetString("LabelYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zip Code.
        /// </summary>
        public static string LabelZipCode {
            get {
                return ResourceManager.GetString("LabelZipCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Card holder name.
        /// </summary>
        public static string PlaceHolderCardholdername {
            get {
                return ResourceManager.GetString("PlaceHolderCardholdername", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Card number.
        /// </summary>
        public static string PlaceHolderCardnumber {
            get {
                return ResourceManager.GetString("PlaceHolderCardnumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CVC.
        /// </summary>
        public static string PlaceHolderCVC {
            get {
                return ResourceManager.GetString("PlaceHolderCVC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string PlaceHolderEmail {
            get {
                return ResourceManager.GetString("PlaceHolderEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Comment.
        /// </summary>
        public static string PlaceHolderEnterComment {
            get {
                return ResourceManager.GetString("PlaceHolderEnterComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zip Code.
        /// </summary>
        public static string PlaceHolderZipCode {
            get {
                return ResourceManager.GetString("PlaceHolderZipCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Enter Comment.
        /// </summary>
        public static string RequiredMsgComment {
            get {
                return ResourceManager.GetString("RequiredMsgComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter CVC.
        /// </summary>
        public static string RequiredMsgCVC {
            get {
                return ResourceManager.GetString("RequiredMsgCVC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter email.
        /// </summary>
        public static string RequiredMsgEmail {
            get {
                return ResourceManager.GetString("RequiredMsgEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select month.
        /// </summary>
        public static string RequiredMsgMonth {
            get {
                return ResourceManager.GetString("RequiredMsgMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter card holder name.
        /// </summary>
        public static string RequiredMsgName {
            get {
                return ResourceManager.GetString("RequiredMsgName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter card number .
        /// </summary>
        public static string RequiredMsgNumber {
            get {
                return ResourceManager.GetString("RequiredMsgNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select Year.
        /// </summary>
        public static string RequiredMsgYear {
            get {
                return ResourceManager.GetString("RequiredMsgYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter zip code.
        /// </summary>
        public static string RequiredMsgZipCode {
            get {
                return ResourceManager.GetString("RequiredMsgZipCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Action.
        /// </summary>
        public static string TableHeaderAction {
            get {
                return ResourceManager.GetString("TableHeaderAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Care Giver.
        /// </summary>
        public static string TableHeaderCareGiver {
            get {
                return ResourceManager.GetString("TableHeaderCareGiver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date of Appointment.
        /// </summary>
        public static string TableHeaderDateofAppointment {
            get {
                return ResourceManager.GetString("TableHeaderDateofAppointment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Patient.
        /// </summary>
        public static string TableHeaderPatient {
            get {
                return ResourceManager.GetString("TableHeaderPatient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reason for Dispute.
        /// </summary>
        public static string TableHeaderReasonforDispute {
            get {
                return ResourceManager.GetString("TableHeaderReasonforDispute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string TableHeaderStatus {
            get {
                return ResourceManager.GetString("TableHeaderStatus", resourceCulture);
            }
        }
    }
}
