//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CaregiverLite.Views.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Layout {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Layout() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CaregiverLite.Views.Resources.Layout", typeof(Layout).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copyright © 2018 Care Giver.
        /// </summary>
        public static string FooterCopyright {
            get {
                return ResourceManager.GetString("FooterCopyright", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pa&lt;strong class=&quot;font-bold&quot;&gt;Seva&lt;/strong&gt;.
        /// </summary>
        public static string HeaderCAREGIVER {
            get {
                return ResourceManager.GetString("HeaderCAREGIVER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Office Manager.
        /// </summary>
        public static string MenuAdmin {
            get {
                return ResourceManager.GetString("MenuAdmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Appointments.
        /// </summary>
        public static string MenuAppointment {
            get {
                return ResourceManager.GetString("MenuAppointment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Caregiver.
        /// </summary>
        public static string MenuCareGiver {
            get {
                return ResourceManager.GetString("MenuCareGiver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Change Password.
        /// </summary>
        public static string MenuChangePassword {
            get {
                return ResourceManager.GetString("MenuChangePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chatting.
        /// </summary>
        public static string MenuChatting {
            get {
                return ResourceManager.GetString("MenuChatting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Conversations.
        /// </summary>
        public static string MenuConversations {
            get {
                return ResourceManager.GetString("MenuConversations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Dashboard.
        /// </summary>
        public static string MenuDashboard {
            get {
                return ResourceManager.GetString("MenuDashboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group Chat.
        /// </summary>
        public static string MenuGroupChat {
            get {
                return ResourceManager.GetString("MenuGroupChat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Office Staff.
        /// </summary>
        public static string MenuNurseCoordinator {
            get {
                return ResourceManager.GetString("MenuNurseCoordinator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Office.
        /// </summary>
        public static string MenuOffice {
            get {
                return ResourceManager.GetString("MenuOffice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Patients Chat Room.
        /// </summary>
        public static string MenuPatientGroupChatting {
            get {
                return ResourceManager.GetString("MenuPatientGroupChatting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Schedule Appointments.
        /// </summary>
        public static string MenuPatientRequest {
            get {
                return ResourceManager.GetString("MenuPatientRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Patients.
        /// </summary>
        public static string MenuPatients {
            get {
                return ResourceManager.GetString("MenuPatients", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Payment Info.
        /// </summary>
        public static string MenuPaymentInfo {
            get {
                return ResourceManager.GetString("MenuPaymentInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Profile.
        /// </summary>
        public static string MenuProfile {
            get {
                return ResourceManager.GetString("MenuProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Reports.
        /// </summary>
        public static string MenuReports {
            get {
                return ResourceManager.GetString("MenuReports", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reward Points.
        /// </summary>
        public static string MenuRewardPoint {
            get {
                return ResourceManager.GetString("MenuRewardPoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reward Points Advance.
        /// </summary>
        public static string MenuRewardPointAdv {
            get {
                return ResourceManager.GetString("MenuRewardPointAdv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Schedules.
        /// </summary>
        public static string MenuSchedule {
            get {
                return ResourceManager.GetString("MenuSchedule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Schedulers.
        /// </summary>
        public static string MenuScheduler {
            get {
                return ResourceManager.GetString("MenuScheduler", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service Types.
        /// </summary>
        public static string MenuServices {
            get {
                return ResourceManager.GetString("MenuServices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Sign Out.
        /// </summary>
        public static string MenuSignOut {
            get {
                return ResourceManager.GetString("MenuSignOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Stripe Account.
        /// </summary>
        public static string MenuStripAccount {
            get {
                return ResourceManager.GetString("MenuStripAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Verification.
        /// </summary>
        public static string MenuVerification {
            get {
                return ResourceManager.GetString("MenuVerification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome to .
        /// </summary>
        public static string TextWelcome {
            get {
                return ResourceManager.GetString("TextWelcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PaSeva.
        /// </summary>
        public static string TitleCareGiver {
            get {
                return ResourceManager.GetString("TitleCareGiver", resourceCulture);
            }
        }
    }
}
