//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CaregiverLite.Views.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class PatientRequest {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal PatientRequest() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CaregiverLite.Views.Resources.PatientRequest", typeof(PatientRequest).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add New.
        /// </summary>
        public static string ButtonAddNew {
            get {
                return ResourceManager.GetString("ButtonAddNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Appointment.
        /// </summary>
        public static string ButtonAddPatientRequest {
            get {
                return ResourceManager.GetString("ButtonAddPatientRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Approve.
        /// </summary>
        public static string ButtonApprove {
            get {
                return ResourceManager.GetString("ButtonApprove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string ButtonCancel {
            get {
                return ResourceManager.GetString("ButtonCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string ButtonCancelRequest {
            get {
                return ResourceManager.GetString("ButtonCancelRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove Filter.
        /// </summary>
        public static string ButtonClearFilter {
            get {
                return ResourceManager.GetString("ButtonClearFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string ButtonClose {
            get {
                return ResourceManager.GetString("ButtonClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string ButtonDelete {
            get {
                return ResourceManager.GetString("ButtonDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter.
        /// </summary>
        public static string ButtonFilter {
            get {
                return ResourceManager.GetString("ButtonFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next.
        /// </summary>
        public static string ButtonNext {
            get {
                return ResourceManager.GetString("ButtonNext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Previous.
        /// </summary>
        public static string ButtonPrevious {
            get {
                return ResourceManager.GetString("ButtonPrevious", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reject.
        /// </summary>
        public static string ButtonReject {
            get {
                return ResourceManager.GetString("ButtonReject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove Selected Appointments.
        /// </summary>
        public static string ButtonRemovePatientAppointmnet {
            get {
                return ResourceManager.GetString("ButtonRemovePatientAppointmnet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Changes.
        /// </summary>
        public static string ButtonSaveChanges {
            get {
                return ResourceManager.GetString("ButtonSaveChanges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update.
        /// </summary>
        public static string ButtonUpdate {
            get {
                return ResourceManager.GetString("ButtonUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From Date:.
        /// </summary>
        public static string FilterLabelFromDate {
            get {
                return ResourceManager.GetString("FilterLabelFromDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Office List.
        /// </summary>
        public static string FilterLabelOffice {
            get {
                return ResourceManager.GetString("FilterLabelOffice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status:.
        /// </summary>
        public static string FilterLabelStatus {
            get {
                return ResourceManager.GetString("FilterLabelStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To Date:.
        /// </summary>
        public static string FilterLabelToDate {
            get {
                return ResourceManager.GetString("FilterLabelToDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Appointment.
        /// </summary>
        public static string HeaderAddPatientRequest {
            get {
                return ResourceManager.GetString("HeaderAddPatientRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Number for closest Caregivers you want.
        /// </summary>
        public static string HeaderNumberOfCaregiver {
            get {
                return ResourceManager.GetString("HeaderNumberOfCaregiver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Number of Miles based on that Caregivers you want .
        /// </summary>
        public static string HeaderNumberOfMiles {
            get {
                return ResourceManager.GetString("HeaderNumberOfMiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Patient Request Details.
        /// </summary>
        public static string HeaderPatientRequestDetail {
            get {
                return ResourceManager.GetString("HeaderPatientRequestDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Appointment List.
        /// </summary>
        public static string HeaderPatientRequestList {
            get {
                return ResourceManager.GetString("HeaderPatientRequestList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From Time.
        /// </summary>
        public static string LabelFromTime {
            get {
                return ResourceManager.GetString("LabelFromTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Speciality.
        /// </summary>
        public static string LabelSpeciality {
            get {
                return ResourceManager.GetString("LabelSpeciality", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To Time.
        /// </summary>
        public static string LabelToTime {
            get {
                return ResourceManager.GetString("LabelToTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to cancel?.
        /// </summary>
        public static string MsgCancelConfirmation {
            get {
                return ResourceManager.GetString("MsgCancelConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete.?.
        /// </summary>
        public static string MsgDeleteConfirmation {
            get {
                return ResourceManager.GetString("MsgDeleteConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Address.
        /// </summary>
        public static string PlaceHolderAddress {
            get {
                return ResourceManager.GetString("PlaceHolderAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter City.
        /// </summary>
        public static string PlaceHolderCity {
            get {
                return ResourceManager.GetString("PlaceHolderCity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Date.
        /// </summary>
        public static string PlaceHolderDate {
            get {
                return ResourceManager.GetString("PlaceHolderDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Description.
        /// </summary>
        public static string PlaceHolderDescription {
            get {
                return ResourceManager.GetString("PlaceHolderDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Medical ID.
        /// </summary>
        public static string PlaceHolderMedicalId {
            get {
                return ResourceManager.GetString("PlaceHolderMedicalId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Number Of Caregiver.
        /// </summary>
        public static string PlaceHolderNumberOfCaregiver {
            get {
                return ResourceManager.GetString("PlaceHolderNumberOfCaregiver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Number Of Miles.
        /// </summary>
        public static string PlaceHolderNumberOfMiles {
            get {
                return ResourceManager.GetString("PlaceHolderNumberOfMiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Password.
        /// </summary>
        public static string PlaceHolderPassword {
            get {
                return ResourceManager.GetString("PlaceHolderPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Patient Name.
        /// </summary>
        public static string PlaceHolderPatientName {
            get {
                return ResourceManager.GetString("PlaceHolderPatientName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter State.
        /// </summary>
        public static string PlaceHolderState {
            get {
                return ResourceManager.GetString("PlaceHolderState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Status.
        /// </summary>
        public static string PlaceHolderStatus {
            get {
                return ResourceManager.GetString("PlaceHolderStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Street.
        /// </summary>
        public static string PlaceHolderStreet {
            get {
                return ResourceManager.GetString("PlaceHolderStreet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Username.
        /// </summary>
        public static string PlaceHolderUserName {
            get {
                return ResourceManager.GetString("PlaceHolderUserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Zip Code.
        /// </summary>
        public static string PlaceHolderZipCode {
            get {
                return ResourceManager.GetString("PlaceHolderZipCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter address.
        /// </summary>
        public static string RequiredMsgAddress {
            get {
                return ResourceManager.GetString("RequiredMsgAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter city.
        /// </summary>
        public static string RequiredMsgCity {
            get {
                return ResourceManager.GetString("RequiredMsgCity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter name.
        /// </summary>
        public static string RequiredMsgName {
            get {
                return ResourceManager.GetString("RequiredMsgName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter state.
        /// </summary>
        public static string RequiredMsgState {
            get {
                return ResourceManager.GetString("RequiredMsgState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter street.
        /// </summary>
        public static string RequiredMsgStreet {
            get {
                return ResourceManager.GetString("RequiredMsgStreet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter zip code.
        /// </summary>
        public static string RequiredMsgZipCode {
            get {
                return ResourceManager.GetString("RequiredMsgZipCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Action.
        /// </summary>
        public static string TableHeaderAction {
            get {
                return ResourceManager.GetString("TableHeaderAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address.
        /// </summary>
        public static string TableHeaderAddress {
            get {
                return ResourceManager.GetString("TableHeaderAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Appointment Date.
        /// </summary>
        public static string TableHeaderAppointmentDate {
            get {
                return ResourceManager.GetString("TableHeaderAppointmentDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Caregiver.
        /// </summary>
        public static string TableHeaderCaregiver {
            get {
                return ResourceManager.GetString("TableHeaderCaregiver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to City.
        /// </summary>
        public static string TableHeaderCity {
            get {
                return ResourceManager.GetString("TableHeaderCity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        public static string TableHeaderDate {
            get {
                return ResourceManager.GetString("TableHeaderDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string TableHeaderDescription {
            get {
                return ResourceManager.GetString("TableHeaderDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fields.
        /// </summary>
        public static string TableHeaderFieldsName {
            get {
                return ResourceManager.GetString("TableHeaderFieldsName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Medical ID.
        /// </summary>
        public static string TableHeaderMedicalId {
            get {
                return ResourceManager.GetString("TableHeaderMedicalId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Patient Name.
        /// </summary>
        public static string TableHeaderPatientName {
            get {
                return ResourceManager.GetString("TableHeaderPatientName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Requested Date.
        /// </summary>
        public static string TableHeaderRequestedDate {
            get {
                return ResourceManager.GetString("TableHeaderRequestedDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scheduler Name.
        /// </summary>
        public static string TableHeaderSchedulerName {
            get {
                return ResourceManager.GetString("TableHeaderSchedulerName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to State.
        /// </summary>
        public static string TableHeaderState {
            get {
                return ResourceManager.GetString("TableHeaderState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string TableHeaderStatus {
            get {
                return ResourceManager.GetString("TableHeaderStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Street.
        /// </summary>
        public static string TableHeaderStreet {
            get {
                return ResourceManager.GetString("TableHeaderStreet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Caregivers Notified.
        /// </summary>
        public static string TableHeaderTotalCaregiversNotified {
            get {
                return ResourceManager.GetString("TableHeaderTotalCaregiversNotified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zip Code.
        /// </summary>
        public static string TableHeaderZipCode {
            get {
                return ResourceManager.GetString("TableHeaderZipCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Schedule Appointments.
        /// </summary>
        public static string TitlePatientRequest {
            get {
                return ResourceManager.GetString("TitlePatientRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zipcode minimum length should be 5.
        /// </summary>
        public static string ValidationMsgZipCode {
            get {
                return ResourceManager.GetString("ValidationMsgZipCode", resourceCulture);
            }
        }
    }
}
