//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CaregiverLite.Views.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Patient {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Patient() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CaregiverLite.Views.Resources.Patient", typeof(Patient).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Appointment.
        /// </summary>
        public static string ButtonAddAppointment {
            get {
                return ResourceManager.GetString("ButtonAddAppointment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ADD PATIENT REQUEST.
        /// </summary>
        public static string ButtonAddPatientRequest {
            get {
                return ResourceManager.GetString("ButtonAddPatientRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string ButtonCancel {
            get {
                return ResourceManager.GetString("ButtonCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel Review.
        /// </summary>
        public static string ButtonCancelReview {
            get {
                return ResourceManager.GetString("ButtonCancelReview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Care Provider.
        /// </summary>
        public static string ButtonChangeCareProvider {
            get {
                return ResourceManager.GetString("ButtonChangeCareProvider", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string ButtonEmail {
            get {
                return ResourceManager.GetString("ButtonEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter.
        /// </summary>
        public static string ButtonFilter {
            get {
                return ResourceManager.GetString("ButtonFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notification.
        /// </summary>
        public static string ButtonNotification {
            get {
                return ResourceManager.GetString("ButtonNotification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reschedule.
        /// </summary>
        public static string ButtonReschedule {
            get {
                return ResourceManager.GetString("ButtonReschedule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SMS.
        /// </summary>
        public static string ButtonSMS {
            get {
                return ResourceManager.GetString("ButtonSMS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submit a Review.
        /// </summary>
        public static string ButtonSubmitReview {
            get {
                return ResourceManager.GetString("ButtonSubmitReview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update.
        /// </summary>
        public static string ButtonUpdate {
            get {
                return ResourceManager.GetString("ButtonUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View.
        /// </summary>
        public static string ButtonView {
            get {
                return ResourceManager.GetString("ButtonView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View Profile.
        /// </summary>
        public static string ButtonViewProfile {
            get {
                return ResourceManager.GetString("ButtonViewProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View Reschedule Request.
        /// </summary>
        public static string ButtonViewRescheduleRequest {
            get {
                return ResourceManager.GetString("ButtonViewRescheduleRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Write Review.
        /// </summary>
        public static string ButtonWriteReview {
            get {
                return ResourceManager.GetString("ButtonWriteReview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Patient Request.
        /// </summary>
        public static string HeaderAddPatientRequest {
            get {
                return ResourceManager.GetString("HeaderAddPatientRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alert Care Giver.
        /// </summary>
        public static string HeaderAlertCareGiver {
            get {
                return ResourceManager.GetString("HeaderAlertCareGiver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alternate Care Provider.
        /// </summary>
        public static string HeaderAlternateCareProvider {
            get {
                return ResourceManager.GetString("HeaderAlternateCareProvider", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Care Giver Details.
        /// </summary>
        public static string HeaderCareGiverDetails {
            get {
                return ResourceManager.GetString("HeaderCareGiverDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Patient Request List.
        /// </summary>
        public static string HeaderPatientRequestList {
            get {
                return ResourceManager.GetString("HeaderPatientRequestList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reschedule.
        /// </summary>
        public static string HeaderReschedule {
            get {
                return ResourceManager.GetString("HeaderReschedule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User List.
        /// </summary>
        public static string HeaderUserList {
            get {
                return ResourceManager.GetString("HeaderUserList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View Details.
        /// </summary>
        public static string HeaderViewDetail {
            get {
                return ResourceManager.GetString("HeaderViewDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View Reschedule appointment request.
        /// </summary>
        public static string HeaderViewRescheduleappointmentrequest {
            get {
                return ResourceManager.GetString("HeaderViewRescheduleappointmentrequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address.
        /// </summary>
        public static string LabelAddress {
            get {
                return ResourceManager.GetString("LabelAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Available.
        /// </summary>
        public static string LabelAvailable {
            get {
                return ResourceManager.GetString("LabelAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Busy.
        /// </summary>
        public static string LabelBusy {
            get {
                return ResourceManager.GetString("LabelBusy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Care Giver List.
        /// </summary>
        public static string LabelCareGiverList {
            get {
                return ResourceManager.GetString("LabelCareGiverList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Care Giver Name.
        /// </summary>
        public static string LabelCareGiverName {
            get {
                return ResourceManager.GetString("LabelCareGiverName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        public static string LabelDate {
            get {
                return ResourceManager.GetString("LabelDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From Date &amp; Time.
        /// </summary>
        public static string LabelFromDateTime {
            get {
                return ResourceManager.GetString("LabelFromDateTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From Time.
        /// </summary>
        public static string LabelFromTime {
            get {
                return ResourceManager.GetString("LabelFromTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hours Rate.
        /// </summary>
        public static string LabelHoursRate {
            get {
                return ResourceManager.GetString("LabelHoursRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hours Rate From.
        /// </summary>
        public static string LabelHoursRateFrom {
            get {
                return ResourceManager.GetString("LabelHoursRateFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To.
        /// </summary>
        public static string LabelHoursRateTo {
            get {
                return ResourceManager.GetString("LabelHoursRateTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No..
        /// </summary>
        public static string LabelNo {
            get {
                return ResourceManager.GetString("LabelNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Patient Name.
        /// </summary>
        public static string LabelPatientName {
            get {
                return ResourceManager.GetString("LabelPatientName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reschedule Status.
        /// </summary>
        public static string LabelRescheduleStatus {
            get {
                return ResourceManager.GetString("LabelRescheduleStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service.
        /// </summary>
        public static string LabelService {
            get {
                return ResourceManager.GetString("LabelService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service Radius.
        /// </summary>
        public static string LabelServiceRadius {
            get {
                return ResourceManager.GetString("LabelServiceRadius", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time Slots.
        /// </summary>
        public static string LabelTimeSlots {
            get {
                return ResourceManager.GetString("LabelTimeSlots", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To Date &amp; Time.
        /// </summary>
        public static string LabelToDateTime {
            get {
                return ResourceManager.GetString("LabelToDateTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Hours.
        /// </summary>
        public static string LabelTotalHours {
            get {
                return ResourceManager.GetString("LabelTotalHours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Payment.
        /// </summary>
        public static string LabelTotalPayment {
            get {
                return ResourceManager.GetString("LabelTotalPayment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To Time.
        /// </summary>
        public static string LabelToTime {
            get {
                return ResourceManager.GetString("LabelToTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select Date.
        /// </summary>
        public static string RequiredMsgDate {
            get {
                return ResourceManager.GetString("RequiredMsgDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select From time.
        /// </summary>
        public static string RequiredMsgFromTime {
            get {
                return ResourceManager.GetString("RequiredMsgFromTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select Hours Rate.
        /// </summary>
        public static string RequiredMsgHourRate {
            get {
                return ResourceManager.GetString("RequiredMsgHourRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select Care Giver.
        /// </summary>
        public static string RequiredMsgNurse {
            get {
                return ResourceManager.GetString("RequiredMsgNurse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select Patient.
        /// </summary>
        public static string RequiredMsgPatient {
            get {
                return ResourceManager.GetString("RequiredMsgPatient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select Service.
        /// </summary>
        public static string RequiredMsgServices {
            get {
                return ResourceManager.GetString("RequiredMsgServices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select To time.
        /// </summary>
        public static string RequiredMsgToTime {
            get {
                return ResourceManager.GetString("RequiredMsgToTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Action.
        /// </summary>
        public static string TableHeaderAction {
            get {
                return ResourceManager.GetString("TableHeaderAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address.
        /// </summary>
        public static string TableHeaderAddress {
            get {
                return ResourceManager.GetString("TableHeaderAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Care Giver Name.
        /// </summary>
        public static string TableHeaderCareGiverName {
            get {
                return ResourceManager.GetString("TableHeaderCareGiverName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        public static string TableHeaderDate {
            get {
                return ResourceManager.GetString("TableHeaderDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string TableHeaderEmail {
            get {
                return ResourceManager.GetString("TableHeaderEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From Date &amp; Time.
        /// </summary>
        public static string TableHeaderFromDateTime {
            get {
                return ResourceManager.GetString("TableHeaderFromDateTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hours Rate.
        /// </summary>
        public static string TableHeaderHoursRate {
            get {
                return ResourceManager.GetString("TableHeaderHoursRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mobile.
        /// </summary>
        public static string TableHeaderMobile {
            get {
                return ResourceManager.GetString("TableHeaderMobile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string TableHeaderName {
            get {
                return ResourceManager.GetString("TableHeaderName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        public static string TableHeaderNo {
            get {
                return ResourceManager.GetString("TableHeaderNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paid Amount.
        /// </summary>
        public static string TableHeaderPaidAmount {
            get {
                return ResourceManager.GetString("TableHeaderPaidAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address.
        /// </summary>
        public static string TableHeaderPatientAddress {
            get {
                return ResourceManager.GetString("TableHeaderPatientAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Patient Name.
        /// </summary>
        public static string TableHeaderPatientName {
            get {
                return ResourceManager.GetString("TableHeaderPatientName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reschedule Status.
        /// </summary>
        public static string TableHeaderRescheduleStatus {
            get {
                return ResourceManager.GetString("TableHeaderRescheduleStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Schedule.
        /// </summary>
        public static string TableHeaderSchedule {
            get {
                return ResourceManager.GetString("TableHeaderSchedule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Services.
        /// </summary>
        public static string TableHeaderServices {
            get {
                return ResourceManager.GetString("TableHeaderServices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time Slot.
        /// </summary>
        public static string TableHeaderTimeSlot {
            get {
                return ResourceManager.GetString("TableHeaderTimeSlot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To Date &amp; Time.
        /// </summary>
        public static string TableHeaderToDateTime {
            get {
                return ResourceManager.GetString("TableHeaderToDateTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Hours.
        /// </summary>
        public static string TableHeaderTotalHours {
            get {
                return ResourceManager.GetString("TableHeaderTotalHours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Payment.
        /// </summary>
        public static string TableHeaderTotalPayment {
            get {
                return ResourceManager.GetString("TableHeaderTotalPayment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zip Code.
        /// </summary>
        public static string TableHeaderZipCode {
            get {
                return ResourceManager.GetString("TableHeaderZipCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current Assigned Care Provider: .
        /// </summary>
        public static string TextCurrentAssigned {
            get {
                return ResourceManager.GetString("TextCurrentAssigned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Users.
        /// </summary>
        public static string TitleUsers {
            get {
                return ResourceManager.GetString("TitleUsers", resourceCulture);
            }
        }
    }
}
