//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CaregiverLite.Views.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class RewardPoint {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal RewardPoint() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CaregiverLite.Views.Resources.RewardPoint", typeof(RewardPoint).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Details.
        /// </summary>
        public static string ButtonDetails {
            get {
                return ResourceManager.GetString("ButtonDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile.
        /// </summary>
        public static string ButtonViewProfile {
            get {
                return ResourceManager.GetString("ButtonViewProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Office:.
        /// </summary>
        public static string FilterOffice {
            get {
                return ResourceManager.GetString("FilterOffice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reward Point Details.
        /// </summary>
        public static string HeaderRewardPointDetail {
            get {
                return ResourceManager.GetString("HeaderRewardPointDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reward Point List.
        /// </summary>
        public static string HeaderRewardPointList {
            get {
                return ResourceManager.GetString("HeaderRewardPointList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Appointment Date.
        /// </summary>
        public static string PopupTableHeaderAppointmentDate {
            get {
                return ResourceManager.GetString("PopupTableHeaderAppointmentDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Appointment Time.
        /// </summary>
        public static string PopupTableHeaderAppointmentTime {
            get {
                return ResourceManager.GetString("PopupTableHeaderAppointmentTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Care Giver Name.
        /// </summary>
        public static string PopupTableHeaderCareGiverName {
            get {
                return ResourceManager.GetString("PopupTableHeaderCareGiverName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Points.
        /// </summary>
        public static string PopupTableHeaderPoints {
            get {
                return ResourceManager.GetString("PopupTableHeaderPoints", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rating.
        /// </summary>
        public static string PopupTableHeaderRating {
            get {
                return ResourceManager.GetString("PopupTableHeaderRating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scheduler Name.
        /// </summary>
        public static string PopupTableHeaderSchedulerName {
            get {
                return ResourceManager.GetString("PopupTableHeaderSchedulerName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comment.
        /// </summary>
        public static string TableHeaderComment {
            get {
                return ResourceManager.GetString("TableHeaderComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Completed Request Count.
        /// </summary>
        public static string TableHeaderCompletedReqCount {
            get {
                return ResourceManager.GetString("TableHeaderCompletedReqCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string TableHeaderName {
            get {
                return ResourceManager.GetString("TableHeaderName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Office.
        /// </summary>
        public static string TableHeaderOffice {
            get {
                return ResourceManager.GetString("TableHeaderOffice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Photo.
        /// </summary>
        public static string TableHeaderPhoto {
            get {
                return ResourceManager.GetString("TableHeaderPhoto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Reward Point.
        /// </summary>
        public static string TableHeaderTotalRewardPoint {
            get {
                return ResourceManager.GetString("TableHeaderTotalRewardPoint", resourceCulture);
            }
        }
    }
}
