//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CaregiverLite.Views.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Stripe {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Stripe() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CaregiverLite.Views.Resources.Stripe", typeof(Stripe).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Access Your Account.
        /// </summary>
        public static string lblAccessYourAccount {
            get {
                return ResourceManager.GetString("lblAccessYourAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Why Stripe is needed ?.
        /// </summary>
        public static string lblWhyStripeisneeded {
            get {
                return ResourceManager.GetString("lblWhyStripeisneeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to - Operations simplified.
        /// </summary>
        public static string PointFive {
            get {
                return ResourceManager.GetString("PointFive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to - Less stripe fees than other payment gateway.
        /// </summary>
        public static string PointFour {
            get {
                return ResourceManager.GetString("PointFour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to - Stripe is faster.
        /// </summary>
        public static string PointOne {
            get {
                return ResourceManager.GetString("PointOne", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to - More secure.
        /// </summary>
        public static string PointThree {
            get {
                return ResourceManager.GetString("PointThree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to - Having a dashboard to easily manage the transaction.
        /// </summary>
        public static string PointTwo {
            get {
                return ResourceManager.GetString("PointTwo", resourceCulture);
            }
        }
    }
}
